INSERT into players(given_name,surname,team,position,points_per_game,rebounds_per_game,assists_per_game,twitter,instagram) VALUES
 ('Isaiah', 'Thomas', 'Celtics', 'PG', 22.2, 3.0, 6.2, 'https://twitter.com/isaiah_thomas', 'https://www.instagram.com/isaiahthomas/'),
 ('Jeremy', 'Lin', 'Nets', 'PG', 11.7, 3.2, 3.0, 'https://twitter.com/jlin7', 'https://www.instagram.com/jlin7/'),
 ('Carmelo', 'Anthony', 'Knicks', 'SF', 21.8, 4.2, 7.7, 'https://twitter.com/carmeloanthony', 'https://www.instagram.com/carmeloanthony/'),
 ('Jahlil', 'Okafor', '76ers', 'C', 17.5, 7.0, 1.2, 'https://twitter.com/jahlilokafor', 'https://www.instagram.com/jah8/'),
 ('Kyle', 'Lowry', 'Raptors', 'PG', 21.2, 4.7, 6.4, 'https://twitter.com/klow7', 'https://www.instagram.com/kyle_lowry7/'),
 ('Jimmy', 'Butler', 'Bulls', 'SF', 20.9, 5.3, 4.8, 'https://twitter.com/jimmybutler', 'https://www.instagram.com/jimmybutler/'),
 ('Kyrie', 'Irving', 'Cavaliers', 'PG', 19.6, 3.4, 5.5, 'https://twitter.com/kyrieirving', 'https://www.instagram.com/kyrieirving/');
